// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("source_map_symbolicator")
	ScopeName = "github.com/honeycombio/opentelemetry-collector-symbolicator/symbolicatorprocessor"
)

const (
	TracesStability = component.StabilityLevelStable
)
