version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/symbolicatorprocessor"
      - "/dsymprocessor"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "maint"
      include: "scope"
    groups:
      aws:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "no-changelog"
    commit-message:
      prefix: "maint"
      include: "scope"
