receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "symbolicator-telemetry-scrape"
          static_configs:
            - targets: ["0.0.0.0:8888"]

processors:
  symbolicator:
  dsymprocessor:
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [symbolicator]
      exporters: [debug]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
