receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  symbolicator:
  dsymprocessor:
    local_dsyms:
      path: ./test_assets
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [symbolicator]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [dsymprocessor, batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
