receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  source_map_symbolicator:
  dsym_symbolicator:
    local_dsyms:
      path: ./test_assets
  proguard_symbolicator:
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [source_map_symbolicator]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [dsym_symbolicator, proguard_symbolicator, batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
