// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("proguard_symbolicator")
	ScopeName = "github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor"
)

const (
	LogsStability = component.StabilityLevelStable
)
