// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetProcessorType sets provided value as "processor_type" attribute.
func (rb *ResourceBuilder) SetProcessorType(val string) {
	if rb.config.ProcessorType.Enabled {
		rb.res.Attributes().PutStr("processor_type", val)
	}
}

// SetProcessorVersion sets provided value as "processor_version" attribute.
func (rb *ResourceBuilder) SetProcessorVersion(val string) {
	if rb.config.ProcessorVersion.Enabled {
		rb.res.Attributes().PutStr("processor_version", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
