// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/honeycombio/opentelemetry-collector-symbolicator/proguardprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                               metric.Meter
	mu                                  sync.Mutex
	registrations                       []metric.Registration
	ProcessorProguardCacheSize          metric.Int64Gauge
	ProcessorSymbolicationDuration      metric.Float64Histogram
	ProcessorTotalFailedFrames          metric.Int64Counter
	ProcessorTotalProcessedFrames       metric.Int64Counter
	ProcessorTotalProguardFetchFailures metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorProguardCacheSize, err = builder.meter.Int64Gauge(
		"otelcol_processor_proguard_cache_size",
		metric.WithDescription("Size of the proguard mapping cache in bytes."),
		metric.WithUnit("{proguardmappings}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSymbolicationDuration, err = builder.meter.Float64Histogram(
		"otelcol_processor_symbolication_duration",
		metric.WithDescription("Duration in seconds taken to symbolicate frames."),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorTotalFailedFrames, err = builder.meter.Int64Counter(
		"otelcol_processor_total_failed_frames",
		metric.WithDescription("Total number of frames the symbolicator failed to symbolicate."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorTotalProcessedFrames, err = builder.meter.Int64Counter(
		"otelcol_processor_total_processed_frames",
		metric.WithDescription("Total number of frames the symbolicator processed."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorTotalProguardFetchFailures, err = builder.meter.Int64Counter(
		"otelcol_processor_total_proguard_fetch_failures",
		metric.WithDescription("Total number of proguard mapping fetch failures."),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
