version: 2.1

orbs:
  go: circleci/go@1.12.0

jobs:
  test:
    docker:
      - image: cimg/golang:1.22
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test

workflows:
  version: 2
  test:
    jobs:
      - test