version: 2.1

orbs:
  go: circleci/go@1.12.0
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@5.1.0

jobs:
  test:
    docker:
      - image: cimg/go:1.22
    steps:
      - add_ssh_keys:
          fingerprints:
            - SHA256:S/ROrHXpQH6H9irqoTBO/T6bKdv0TLepe2KjL5v32SM
      - checkout
      - run:
          name: Run unit tests
          command: make test
          environment:
            GOPRIVATE: github.com/honeycombio/symbolic-go
  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "Creating GitHub release for tag ${CIRCLE_TAG}"
            ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG}
workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test

  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish_github:
          context: Honeycomb Secrets for Public Repos
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
      - aws-ecr/build_and_push_image:
          # filters:
          #   branches:
          #     only:
          #       - main
          auth:
            - aws-cli/setup:
                role_arn: "arn:aws:iam::702835727665:role/circleci-deploy"
                role_session_name: "collector-symbolicator-processor"
                region: us-east-1
          account_id: "702835727665"
          region: "us-east-1"
          repo: collector-symbolicator-processor
          tag: "${CIRCLE_SHA1}"
          platform: linux/arm64